---
name: Lint Code Base
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  action-linter:
    timeout-minutes: 5
    name: Action Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cschleiden/actions-linter@v1
        with:
          workflows: '[".github/workflows/*.yml"]'

  repo-linter:
    timeout-minutes: 10
    name: SuperLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4.6.1
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSCPD: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
